# Generated by Django 5.1.4 on 2024-12-26 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellidos", models.CharField(blank=True, max_length=100, null=True)),
                ("telefono_uno", models.CharField(max_length=15)),
                (
                    "telefono_dos",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("compañia", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("date", models.DateTimeField(default=datetime.date.today)),
                ("nots", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
