# Generated by Django 5.1.4 on 2024-12-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contactos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacto",
            old_name="nots",
            new_name="notas",
        ),
    ]
