# Generated by Django 5.1.4 on 2024-12-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contactos", "0002_rename_nots_contacto_notas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacto",
            old_name="telefono_dos",
            new_name="movil",
        ),
        migrations.RenameField(
            model_name="contacto",
            old_name="telefono_uno",
            new_name="telefono",
        ),
    ]
