# Generated by Django 5.1.4 on 2025-01-09 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactos", "0003_rename_telefono_dos_contacto_movil_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacto",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
