# Generated by Django 5.1.4 on 2024-12-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toDo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TasK",
            new_name="ToDo",
        ),
    ]
