# Generated by Django 5.1.4 on 2025-01-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toDo", "0003_todo_tiempo_estimado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="tiempo_estimado",
        ),
    ]
