# Generated by Django 5.1.4 on 2025-01-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toDo", "0004_remove_todo_tiempo_estimado"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="tiempo_estimado",
            field=models.IntegerField(default=3),
        ),
    ]
